package io.github.reinershir.ai.service.impl;


import org.springframework.stereotype.Service;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;

import io.github.reinershir.ai.mapper.ChatHistoryMapper;
import io.github.reinershir.ai.model.ChatHistory;
import io.github.reinershir.ai.service.ChatHistoryService;

/**
 * ChatHistory Service, generated by Shir Boot
 * @author Shir-Boot
 * @Date 2024年4月17日 上午10:07:25
 * @version 1.0		
 * 
 */
@Service("chatHistoryService")
public class ChatHistoryServiceImpl extends ServiceImpl<ChatHistoryMapper,ChatHistory> implements ChatHistoryService{


}
