package io.github.reinershir.ai.service.impl;


import org.springframework.stereotype.Service;

import io.github.reinershir.ai.model.Mask;
import io.github.reinershir.ai.service.MaskService;
import io.github.reinershir.ai.mapper.MaskMapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;

/**
 * Mask Service, generated by Shir Boot
 * @author Shir-Boot
 * @Date 2024年4月17日 上午10:40:16
 * @version 1.0		
 * 
 */
@Service("maskService")
public class MaskServiceImpl extends ServiceImpl<MaskMapper,Mask> implements MaskService{


}
