package io.github.reinershir.boot.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import io.github.reinershir.boot.model.Dictionary;
import org.springframework.stereotype.Repository;
/**
 * dictionary Mapper, generated by Shir Boot
 * @author Shir-Boot
 **/
 @Repository
public interface DictionaryMapper extends BaseMapper<Dictionary> {

}
