package io.github.reinershir.boot.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import io.github.reinershir.boot.model.Suggestions;
import org.springframework.stereotype.Repository;
/**
 * 投诉建议 Mapper, generated by MyBatisGenerator
 * @author Shir-Boot
 * @version 1.0
 **/
 @Repository
public interface SuggestionsMapper extends BaseMapper<Suggestions> {

}
