package io.github.reinershir.boot.mapper;

import org.springframework.stereotype.Repository;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import io.github.reinershir.boot.model.User;
/**
 * 用户 Mapper, generated by MyBatisGenerator
 * @author Shir-Boot
 * @version 1.0
 **/
 @Repository
public interface UserMapper extends BaseMapper<User> {

}
