package io.github.reinershir.boot.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import io.github.reinershir.boot.User;
import org.springframework.stereotype.Repository;
/**
 * 用户 Mapper, generated by MyBatisGenerator
 * @author Shir-Boot
 * @version 1.0
 **/
 @Repository
public interface UserMapper extends BaseMapper<User> {

}
