package io.github.reinershir.boot.service;
import com.baomidou.mybatisplus.extension.service.IService;
import io.github.reinershir.boot.model.Suggestions;

/**
 * Suggestions Service, generated by Shir Boot EasyGenerator
 * @author Shir-Boot
 * @version 1.0
 *
 */
public interface SuggestionsService extends IService<Suggestions>{
	
}
