package io.github.reinershir.boot.service.impl;


import org.springframework.stereotype.Service;

import io.github.reinershir.boot.model.Dictionary;
import io.github.reinershir.boot.service.DictionaryService;
import io.github.reinershir.boot.contract.DictionaryCodes;
import io.github.reinershir.boot.mapper.DictionaryMapper;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;

/**
 * Dictionary Service, generated by Shir Boot
 * @author Shir-Boot
 * @Date 2024年1月20日 下午4:56:15
 * @version 1.0		
 * 
 */
@Service("dictionaryService")
public class DictionaryServiceImpl extends ServiceImpl<DictionaryMapper,Dictionary> implements DictionaryService{

	@Override
	public String getValueByCode(DictionaryCodes code) {
		return baseMapper.selectOne(new LambdaQueryWrapper<Dictionary>().eq(Dictionary::getCode, code)).getValue();
	}

	
}
