package io.github.reinershir.boot.service.impl;


import org.springframework.stereotype.Service;

import io.github.reinershir.boot.model.Suggestions;
import io.github.reinershir.boot.service.SuggestionsService;
import io.github.reinershir.boot.mapper.SuggestionsMapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;

/**
 * Suggestions Service, generated by Shir Boot EasyGenerator
 * @author Shir-Boot
 * @version 1.0
 * 
 */
@Service("suggestionsService")
public class SuggestionsServiceImpl extends ServiceImpl<SuggestionsMapper,Suggestions> implements SuggestionsService{


}
