package io.github.reinershir.boot.service.impl;


import org.springframework.stereotype.Service;

import io.github.reinershir.boot.model.SystemLog;
import io.github.reinershir.boot.service.SystemLogService;
import io.github.reinershir.boot.mapper.SystemLogMapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;

/**
 * SystemLog Service, generated by Shir Boot EasyGenerator
 * @author Shir-Boot
 * @version 1.0
 * 
 */
@Service("systemLogService")
public class SystemLogServiceImpl extends ServiceImpl<SystemLogMapper,SystemLog> implements SystemLogService{


}
