package io.github.reinershir.boot.model;

import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import io.github.reinershir.boot.common.ValidateGroups;
import io.github.reinershir.boot.core.query.annotation.QueryRule;
import io.github.reinershir.boot.core.query.annotation.QueryRuleEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
/**
 * Dictionary Model, generated by Shir Boot 
 * @author Shir-Boot
 * @Date 2024年1月20日 下午4:56:15
 * @version 1.0
 *
 */
 @Data
 @TableName("DICTIONARY")
public class Dictionary {
	/**
	 * 
	 */
	@TableId(type=IdType.AUTO)
	@Schema(description = "Dictionary ID")
	@NotNull(message = "id不能为空",groups = ValidateGroups.UpdateGroup.class)
	private Integer id;
	
	/**
	 * 
	 */
	@Schema(description = "name")
	@NotBlank(message = "name不能为空",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
	private String name;
	
	/**
	 * dictionary code
	 */
	@Schema(description = "dictionary code")
	@NotBlank(message = "dictionary code不能为空",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
	private String code;
	
	/**
	 * dictionary value
	 */
	@Schema(description = "dictionary value")
	@NotBlank(message = "dictionary value不能为空",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
	private String value;
	
	/**
	 * code type fill in system or custom
	 */
	@Schema(description = "code type fill in SYSTEM or CUSTOM",nullable = true,defaultValue="SYSTEM")
	private String type;
	
	
	
}
