package io.github.reinershir.boot.model;

import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import io.github.reinershir.boot.common.ValidateGroups;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
/**
/**
 * Suggestions Model, generated by Shir Boot 
 * @author Shir-Boot
 * @Date 2023年8月19日 下午5:44:42
 * @version 1.0
 *
 */
 @Data
 @TableName("SUGGESTIONS")
public class Suggestions {

	/**
	 * 
	 */
	@TableId(type=IdType.AUTO)
	@Schema(description = "Suggestions ID")
	@NotNull(message = "id不能为空",groups = ValidateGroups.UpdateGroup.class)
	private Long id;
	
	/**
	 * 内容
	 */
	@Schema(description = "内容")
	@NotBlank(message = "内容不能为空",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
	private String content;
	
	/**
	 * 类型，1=功能缺陷2=政策资讯3=其它问题
	 */
	@Schema(description = "类型，1=功能缺陷2=政策资讯3=其它问题",nullable = true,defaultValue="0")
	private Integer type;
	
	/**
	 * 上传的图片地址
	 */
	@Schema(description = "上传的图片地址")
	private String images;
	
	/**
	 * 联系方式
	 */
	@Schema(description = "联系方式")
	private String address;
	
	/**
	 * 用户ID
	 */
	@Schema(description = "用户ID",nullable = true,defaultValue="0")
	private Long userId;
	
	/**
	 * 
	 */
	@Schema(description = "createTime")
	private Date createTime;
	
	
	
}
