package io.github.reinershir.boot.model;

import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import io.github.reinershir.boot.common.ValidateGroups;
import io.github.reinershir.boot.core.query.annotation.QueryRule;
import io.github.reinershir.boot.core.query.annotation.QueryRuleEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
/**
 * SystemLog Model, generated by Shir Boot 
 * @author Shir-Boot
 * @Date 2023年12月7日 下午6:59:47
 * @version 1.0
 *
 */
 @Data
 @TableName("SYSTEM_LOG")
public class SystemLog {
	/**
	 * 
	 */
	@TableId(type=IdType.AUTO)
	@Schema(description = "SystemLog ID")
	@NotNull(message = "id不能为空",groups = ValidateGroups.UpdateGroup.class)
	private Long id;
	
	/**
	 * 请求接口名称
	 */
	@Schema(description = "请求接口名称")
	@NotBlank(message = "请求接口名称不能为空",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
	private String requestName;
	
	/**
	 * 请求路径
	 */
	@QueryRule(QueryRuleEnum.LIKE)
	@Schema(description = "请求路径")
	@NotBlank(message = "请求路径不能为空",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
	private String requestUri;
	
	/**
	 * 请求参数体
	 */
	@Schema(description = "请求参数体")
	private String requestBody;
	
	/**
	 * 请求用户ID
	 */
	@Schema(description = "请求用户ID")
	private Long requestUserId;
	
	/**
	 * 请求用户名称
	 */
	@Schema(description = "请求用户名称")
	private String requestUser;
	
	/**
	 * 请求IP地址
	 */
	@Schema(description = "请求IP地址")
	private String requestIp;
	
	/**
	 * 创建时间
	 */
	@Schema(description = "创建时间")
	private Date createTime;
	
	/**
	 * 请求标识ID
	 */
	@Schema(description = "请求标识ID")
	private String requestId;
	
	
	
}
