package io.github.reinershir.ai.model;

import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import io.github.reinershir.boot.common.ValidateGroups;
import io.github.reinershir.boot.core.query.annotation.QueryRule;
import io.github.reinershir.boot.core.query.annotation.QueryRuleEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
/**
 * Mask Model, generated by Shir Boot 
 * @author Shir-Boot
 * @Date 2024年4月17日 上午10:40:16
 * @version 1.0
 *
 */
 @Data
 @TableName("MASK")
public class Mask {
	/**
	 * 
	 */
	@TableId(type=IdType.AUTO)
	@Schema(description = "Mask ID")
	@NotNull(message = "id不能为空",groups = ValidateGroups.UpdateGroup.class)
	private Long id;
	
	/**
	 * 
	 */
	@QueryRule(QueryRuleEnum.LIKE)
	@Schema(description = "maskName")
	@NotBlank(message = "maskName不能为空",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
	private String maskName;
	
	/**
	 * 
	 */
	@Schema(description = "prompt")
	@NotBlank(message = "prompt不能为空",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
	private String prompt;
	
	/**
	 * 
	 */
	@Schema(description = "size")
	private Integer size;
	
	/**
	 * 
	 */
	@Schema(description = "createTime")
	private Date createTime;
	
	
	
}
