package ${commonPath}.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import ${modelPackage}.${ClassName};
import org.springframework.stereotype.Repository;
/**
 * ${modelDescription} Mapper, generated by Shir Boot
 * @author Shir-Boot
 **/
 @Repository
public interface ${ClassName}Mapper extends BaseMapper<${ClassName}> {

}
