package ${modelPackage}.model;

import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import io.github.reinershir.boot.common.ValidateGroups;
import io.github.reinershir.boot.core.query.annotation.QueryRule;
import io.github.reinershir.boot.core.query.annotation.QueryRuleEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
/**
 * ${ClassName} Model, generated by Shir Boot 
 * @author Shir-Boot
 * @Date ${.now}
 * @version 1.0
 *
 */
 @Data
 @TableName("${tableName}")
public class ${ClassName} {
	<#if entityInfo??>
	<#list entityInfo.fields as item>
	<#if item.comment??>
	/**
	 * ${item.comment}
	 */
	 </#if>
	<#if item.operation ?? && item.operation != ''>
	<#assign anno = generateUtil.generateAnnotation(item.operation)!>
	${anno}
	</#if>
	<#if item.isPrimaryKey == true>
	<#-- ID 注解 -->
	@TableId(type=IdType.AUTO)
	@Schema(description = "${ClassName} ID")
	<#if item.javaType == 'String'>
	@NotBlank(message = "${(item.comment!='')?string(item.comment,item.name)}<@messages code='message.notnull'/>",groups = ValidateGroups.UpdateGroup.class)
		<#else>
	@NotNull(message = "${(item.comment!='')?string(item.comment,item.name)}<@messages code='message.notnull'/>",groups = ValidateGroups.UpdateGroup.class)
		</#if>
	</#if>
	<#-- 不是ID且 字段不能为空 -->
	<#if item.isPrimaryKey == false && item.isNull == false && item.name != 'createTime'>
		<#if item.defaultValue??>
	<#-- 如果可为空且有默认值 -->
	@Schema(description = "${(item.comment!='')?string(item.comment,item.name)}",nullable = true,defaultValue="${item.defaultValue}")
		<#else>
	@Schema(description = "${(item.comment!='')?string(item.comment,item.name)}")
	<#--如果是字符串类型-->
		<#if item.javaType == 'String'>
	@NotBlank(message = "${(item.comment!='')?string(item.comment,item.name)}<@messages code='message.notnull'/>",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
		<#else>
	@NotNull(message = "${(item.comment!='')?string(item.comment,item.name)}<@messages code='message.notnull'/>",groups = {ValidateGroups.AddGroup.class,ValidateGroups.UpdateGroup.class})
		</#if>
	</#if>
		<#else>
	<#if item.isPrimaryKey == false>
	@Schema(description = "${(item.comment ?? && item.comment != '')? then(item.comment,item.name)}")
	</#if>
	</#if>
	private ${item.javaType} ${item.name};
	
	</#list>
	</#if>
	
	
	<#-- <#if entityInfo??>
	<#list entityInfo.fields as item>
	public void set${item.name ? cap_first} (${item.javaType} ${item.name}){
		this.${item.name} = ${item.name};
	}
	
	public ${item.javaType} get${item.name ? cap_first} (){
		return this.${item.name};
	}
	
	</#list>
	</#if> -->
}
