package ${pkgName}.service.impl;


import org.springframework.stereotype.Service;

import ${pkgName}.model.${ClassName};
import ${pkgName}.service.${ClassName}Service;
import ${pkgName}.mapper.${ClassName}Mapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;

/**
 * ${ClassName} Service, generated by Shir Boot
 * @author Shir-Boot
 * @Date ${.now}
 * @version 1.0		
 * 
 */
@Service("${ClassName?uncap_first}Service")
public class ${ClassName}ServiceImpl extends ServiceImpl<${ClassName}Mapper,${ClassName}> implements ${ClassName}Service{


}
