package ${pkgName}.service;
import com.baomidou.mybatisplus.extension.service.IService;
import ${pkgName}.model.${ClassName};

/**
 * ${ClassName} Service, generated by Shir Boot EasyGenerator
 * @author Shir-Boot
 * @version 1.0
 *
 */
public interface ${ClassName}Service extends IService<${ClassName}>{
	
}
