package io.github.reinershir.ai.service;
import com.baomidou.mybatisplus.extension.service.IService;
import io.github.reinershir.ai.model.ChatHistory;

/**
 * ChatHistory Service, generated by Shir Boot EasyGenerator
 * @author Shir-Boot
 * @version 1.0
 *
 */
public interface ChatHistoryService extends IService<ChatHistory>{
	
}
