package io.github.reinershir.ai.service;
import com.baomidou.mybatisplus.extension.service.IService;
import io.github.reinershir.ai.model.Mask;

/**
 * Mask Service, generated by Shir Boot EasyGenerator
 * @author Shir-Boot
 * @version 1.0
 *
 */
public interface MaskService extends IService<Mask>{
	
}
