package io.github.reinershir.ai.mapper;

import org.springframework.stereotype.Repository;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import io.github.reinershir.ai.model.Mask;
/**
 * mask Mapper, generated by Shir Boot
 * @author Shir-Boot
 **/
 @Repository
public interface MaskMapper extends BaseMapper<Mask> {

}
